name: datastore_test
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amplify_core: 0.0.1-dev.6
  amplify_datastore: 0.0.1-dev.6

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer:
  pedantic:

dependency_overrides:
  amplify_core:
    path: ../amplify-flutter/packages/amplify_core
  amplify_datastore:
    path: ../amplify-flutter/packages/amplify_datastore

flutter:
  uses-material-design: true
