name: datastore_test
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: 0.0.2-dev.1
  amplify_datastore: 0.0.2-dev.1

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer:
  pedantic:

flutter:
  uses-material-design: true
